### ISSUE TITLE
Peer2peer review 16/12/2021

### ISSUE THREAD

**Issue by williamrolando88** [Anjacodes/Leaderboard#3]
Hi, Anja 👋 

I like the simplicity in your code it is so clear and easy to understand, nice job 😄. Here I have some recommendations for improvement in your code:

- In the following line it would be a good idea to pass the data to `textContent` as a string instead of `innerHTML` to prevent users to inject malicious code directly into your API https://github.com/Anjacodes/Leaderboard/blob/c85376d8aca5ffd19ae9cbfcc626fbe79dcfc58a/src/index.js#L50
- In `index.html` it would be a good idea to change the title https://github.com/Anjacodes/Leaderboard/blob/c85376d8aca5ffd19ae9cbfcc626fbe79dcfc58a/src/index.html#L10

Happy coding 🍀

**Comment by Anjacodes** [comment]
Thank you, @williamrolando88 for your helpful feedback!
I have implemented the suggested changes 👍
